### ISSUE TITLE
[sentry error] IllegalStateException - observation related failure on android

### ISSUE THREAD

**Issue by yuliadub** [stevekuznetsov/avalanche-forecast#248]
IllegalStateException android.view.ViewGroup in addViewInner, 
The specified child already has a parent. You must call removeView() on the child's parent first.

2 instances, looks like on observation submission
https://nwac.sentry.io/issues/3971707039/?project=4504317393436672&query=is%3Aunresolved&referrer=issue-stream
https://nwac.sentry.io/issues/3974679389/?project=4504317393436672&query=is%3Aunresolved&referrer=issue-stream

**Comment by stevekuznetsov** [comment]
This is caused when you put something as a child of `<MapView>` that isn't from the `react-native-maps` library - we hit this issue in other components in the past. However, in this case, there is no errant child. This doesn't reproduce on my device, either, and was a 100% reproducible rendering failure otherwise. Closing for now, let's see if we see it again (have not seen it for two weeks).
