### ISSUE TITLE
Figure out our approach to date-based browsing

### ISSUE THREAD

**Issue by floatplane** [stevekuznetsov/avalanche-forecast#89]
Questions include:

1. do we browse data at a given datetime, or at a given day?
2. how do we define a day? if we have a "current day", does it implicitly refer to the previous 24 hours or the next 24?
    a. brian: I would naively think it's the next 24 - that you want forecasts that overlap with the hours in front of you, and not the hours behind you
4. for any given 24 hour period, there will certainly be multiple forecasts available -  I think this is non-controversial - so we have to handle that (and we do, by always grabbing the first one returned from NAC)
5. for a single point in time, there should be only one forecast available - but this is not enforced as far as we can tell, and there may be cases where multiple matches appear
6. if you start the app 30 seconds before midnight UTC, what should your experience be as you continue to browse? at some point, we'd want to adjust the notion of `defaultDate`, since it would affect queries like this one:
https://github.com/stevekuznetsov/avalanche-forecast/blob/b2db8f21a506a2a909c8181aa7fabfe2baa1f3bc/hooks/useAvalancheForecastFragments.ts#L41-L49
7. if you start the app 30 seconds before a forecast expires, what should your experience be as you continue to browse? 
  a. should our calls to `useQuery` pick caching intervals that are based on the forecast expiration time? (is that even possible?)
  b. how do we avoid showing stale forecasts?

cc @stevekuznetsov

**Comment by stevekuznetsov** [comment]
1. do we browse data at a given datetime, or at a given day?

In order to browse at a given "day", we need to define a mapping from every date-time to a "day". This obviously cannot be the naive approach of truncating more specific data from a date-time, since we need 5:59pm and 6:01pm to map to different "day"s for NWAC.

IF we want to trust that the expiry time is correct:

```
$ curl -s https://api.avalanche.org/v2/public/avalanche-center/NWAC | jq '.config.expires_time'
18
```

We can define this mapping as a floor function, but we risk having mangled output when the published forecasts don't adhere to this expiry time.

---

If, instead, we browse at a specific moment in time, this dove-tails with question 6... We have a couple scenarios:

Cases where we expect to use cached, previous data:

- a user requesting the forecast at 2:00:00pm and 2:00:01pm
- a user requesting the forecast at 6:00am (online) and 9:00am (offline)

Cases where we do *not* expect to use the cached, previous state:

 - a user requesting the forecast at 5:59pm and 6:01pm
 - a user requesting the forecast _before_ and _after_ a revised forecast is published for a zone

---

Let's run the logical train of thought about revised forecasts. If we assume that we want the app to show the revised forecast immediately after it's available, even when previously-cached data exists for that time, we imply that no caching is allowed. I think it's not controversial to say that this is not an acceptable outcome, since we don't want every screen navigation in the app to require another network request. Let's investigate what happens if, instead, we simply have `react-query` do the fetch in the background and update our view if something's changed. We would have two cases:

- the app has push notifications working and they have driven a background data load of the revised forecast before the user requests it, so the user sees the revised forecast from the moment they open the app
- [else] the user sees their zone map or forecast screen update after they first opened it - this is not ideal UX but likely workable, especially if we overlay some info icon on the map to make it visually obvious that something changed. Possible reasons for us hitting this case:
  - the app has not matured enough to have push notifications yet
  - the push notification system failed entirely to deliver the payload
  - the user is requesting the revised forecast in the short time window between a forecast being revised and the push notification being delivered to the app

It seems (at least to me) reasonable given the above to allow caching the calls and handle revised forecasts as noted.

---

Without the revised forecast case, we are left with the three other scenarios above. The 5:59pm to 6:01pm case is likely the most interesting one - the more general statement would be that a user who has  recently viewed the previous forecast should not see it when looking at the app again momentarily later if a newer forecast exists, regardless of the expiry time. Let's investigate what would occur if we passed to `react-query` the following tuple for cache key: `(center_id, start_date, end_date, nominal_date)`, where `nominal_date` is the floor function applied to the current date-time as mentioned above. We need to be vague (but consistent) with how we define the start and end times for the query, since we don't know when the valid forecasts are published relative to when we search for them, and the query we have in the API is over published time, not valid time [xref](https://github.com/NationalAvalancheCenter/avalanche.org-API/blob/d938bf74fc4db0c8e8262e80a21e9c58a1b133fc/app/src/Classes/AvalancheForecast.php#L386-L394). We could determine these keys with:

```js
function cacheKey(centerID: AvalancheCenterID, expiryTimeHours: number, requestedTime: Date) string[] {
    return [
        centerID,
        startOfDay(sub(requestedTime, {days: 1})), // the start of the day before the query
        endOfDay(requestedTime), // the end of the day of the query
        nominalDay(expiryTimeHours, requestedTime)
    ];
}

function nominalDay(expiryTimeHours: number, requestedTime: Date): Date {
    if isAfter(add(startOfDay(requestedTime), {hours: expiryTimeHours}), requestedTime) {
        return startOfDay(requestedTime);
    } else {
        return add(startOfDay(requestedTime), {days: 1};
    }
}
```

For example, for NWAC with a 6pm expiry time, we would get these cache keys:

- `1/2/01 5:59pm -> [NWAC, 1/1/01 0:00, 1/2/01 23:59, 1/1/01]` (true for all moments that day up to that time)
- `1/2/01 6:01pm -> [NWAC, 1/1/01 0:00, 1/2/01 23:59, 1/2/01]` (true for all moments that day after that time)

Therefore, we'd re-use the cache up until the change-over, but not after it.

---

The only downside to this approach would be when forecasters do not align their publication and expiry times with the expected value in the center's metadata. I checked the staging environment and when publishing a forecast, these times get auto-filled for you but you are free to change them. If the forecast was still published in our vague date range, this gracefully degrades to the same case as the revised forecast above.

**Comment by stevekuznetsov** [comment]
Another tension here is that we're interested in querying the forecasts for those that are valid at a given point in time, irrespective of when they are published. The forecast fragments API does not give us this ability. We *could* look into ditching it altogether and using the "current forecast" API, with cache keys `(center_id, nominal_date)` to make it cache-able but give us that switch-over functionality as well. IIRC we can alias the data from that endpoint to the "get forecast by ID" query, so our views can still be driven by "view forecast by ID" logic, but we only would need to fetch a forecast once.

**Comment by stevekuznetsov** [comment]
Started fixing this in #98

**Comment by stevekuznetsov** [comment]
We have a clear distinction between `latest` and specific date-time queries on all of our calls now, I believe this is done.
